### ISSUE TITLE
move to JuliaRegistries

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaRegistries/Registrator.jl#126]
As a part of the open-source infrastructure for Julia's registration process, this should be moved to the @JuliaRegistries org. @nkottary, will it break anything if we move this repo?

**Comment by nkottary** [comment]
No, it will not break anything. I will move it.

**Comment by nkottary** [comment]
It looks like I don't have the access rights to transfer this repository.

**Comment by StefanKarpinski** [comment]
Ok, done. Let's see what chaos ensues... Hopefully none?
