### ISSUE TITLE
Unexpected error: Release between two releases

### ISSUE THREAD

**Issue by Wikunia** [JuliaRegistries/Registrator.jl#128]
We are currently trying to register a new release for Juniper:
https://github.com/lanl-ansi/Juniper.jl/issues/125

There is an unexpected error comment by the bot. I suppose it has something to do with the two release branches we have. We have a release-0.2 branch and the master on v0.4.0. Our goal was to have the v0.3.0 release for a breaking change from v0.2.
In more detail:
v0.2 - julia > v0.6 and MathProgBase
v0.4 - julia > v1.0 and MathOptInterface

now we want to have v0.3 for julia >1.0 and MathProgBase

In general it would be nice to have a way to get more feedback on the error.

**Comment by StefanKarpinski** [comment]
@nkottary, can you take a look?

**Comment by nkottary** [comment]
Looking into it right now.

**Comment by nkottary** [comment]
The issue was that we use julia's parser to parse release-0.3 and it gets parsed as an expression
release - 0.3 instead of as a string.

This is fixed now.

**Comment by StefanKarpinski** [comment]
Which commit fixed this?

**Comment by nkottary** [comment]
Fixed by 15a9f26670304637da8790b28737564dbef537ad and c5804e81188fc80aec78758d3e0619c769bf82bd

**Comment by StefanKarpinski** [comment]
I'm not quite following the fix. What happens now if someone does `@JuliaRegistrator register(branch=release-0.3)`? Do they get an error?

**Comment by nkottary** [comment]
They will get the `Unexpected error...` which is why I've updated the documentation in the README.

We will need to write a better `register()` parser to get better error messages.

**Comment by StefanKarpinski** [comment]
Ok. Should we open an issue about better `register` parsing? We could probably stand to spend some time on designing the syntax of that a bit. It's currently in a bit of a no-man's land between Julia code and a command-line syntax. I feel like Julia syntax is way too much for bot interactions.

**Comment by nkottary** [comment]
Okay, I will open an issue for that.

**Comment by nkottary** [comment]
https://github.com/JuliaRegistries/Registrator.jl/issues/130
