### ISSUE TITLE
Rethink the trigger command

### ISSUE THREAD

**Issue by nkottary** [JuliaRegistries/Registrator.jl#130]
Currently we use a some what julia syntax to express keyword arguments to the trigger. Ex.:

```
@JuliaRegistrator register(target="SomeRegistry", branch="release")
```

Which seems too complex. Maybe a simpler alternative would be to mention the arguments line by line:

```
@JuliaRegistrator register()

/branch release
/target MyRegistry
```

Thoughts?

**Comment by iamed2** [comment]
What is too complex?

**Comment by nkottary** [comment]
Using julia syntax :)

**Comment by christopher-dG** [comment]
IMO there's no great syntax that we can achieve with a GitHub comment, but I do think that using pretend code is awkward. I'd prefer your proposed syntax, although I'd get rid of the `()` as well. 
But I don't think that's really worth triggering the annoyance of everyone by yet another breaking workflow change. 
If only we could use an interface more specialized for filling out and submitting forms :stuck_out_tongue_winking_eye:.

**Comment by oxinabox** [comment]
Triggering the parser seems like it is exposing a lot of code that has not been security hardenned to the wild world.

**Comment by christopher-dG** [comment]
Yeah, if we do want to keep existing syntax to avoid annoying people, it would be easy to parse via a regex.

**Comment by christopher-dG** [comment]
I'll close this for now since I think the new parser is acceptable, feel free to reopen if there's more to say.
