### ISSUE TITLE
Patch notes

### ISSUE THREAD

**Issue by christopher-dG** [JuliaRegistries/Registrator.jl#137]
Context: https://github.com/JuliaRegistries/TagBot/issues/8

So basically, the above issue proposes that you should be able to write your patch notes in your Registrator comment and have them propagated to your Git tag and GitHub release. I think this is a really nice idea.

Currently I don't see many people editing their TagBot-created GitHub releases with patch notes, and having the notes on both the tag and the release is a good practice. As is mentioned in the linked issue, Pkg could also start to display patch notes to users so that they know what to expect when upgrading stuff (I think I've seen package authors asking about ways to do this in the past as well).

Ideally, Registrator could copy the notes from the trigger point into its PR so that TagBot doesn't need to go looking for other commit comments or issues or PRs, not to mention the web UI doesn't have any point of reference to look back to. If not for this, the feature could be implemented solely on TagBot's end. 

There are a few syntax suggestions in the linked issue. I'm not really sure which one I like best, but #130 is somewhat relevant here because putting a multiline string in some pretend code would be a nightmare.

In any case, this is just to assess interest and if it seems like a good idea I can start implementing it on both Registrator and TagBot.

**Comment by nkottary** [comment]
Fixed by #147
