### ISSUE TITLE
WebUI has no way to set depedency registries

### ISSUE THREAD

**Issue by BenJWard** [JuliaRegistries/Registrator.jl#140]
Unlike the bot (thanks to #64 & #67), the WebUI has no way to use `registry_deps`, when it calls the `RegEdit.register` method.

The Bot server uses a config file, but the WebUI uses a series of environmental variables. Could we add a REG_DEPS environment variable?

I'm not sure how to pass array values as an ENV variable - when I've tried `export testvar=("hi", "testing")` and started julia, such a variable does not appear in ENV. Perhaps we could just use a string that is a comma-separated list of urls for the registry_deps?

I'm happy to make a PR implementing such a thing, and test the WebUI on Heroku if that is desirable.

**Comment by christopher-dG** [comment]
Usually lists as environment variables just appear as space or comma-delimited strings, like you mentioned. If you do a PR, please call the variable `REGISTRY_DEPS` to be a bit more clear 🙂.

**Comment by BenJWard** [comment]
Ok, I'll give it a go! :)

**Comment by nkottary** [comment]
I think we should keep all config in the TOML file in `image/scripts/sample.toml` instead of having them be environment variables. Its good to have config in one place. Things like lists also have a clear syntax in TOML.

**Comment by nkottary** [comment]
Fixed by #152

**Comment by BenJWard** [comment]
Thanks! :)
