### ISSUE TITLE
Error reading Project.toml: Malformed UUID string

### ISSUE THREAD

**Issue by Eetion** [JuliaRegistries/Registrator.jl#153]
Got the following comment from JuliaRegistrator after attempting to register (via commenting `@JuliaRegistrator register(branch="1.1compat")` in an issue report)
```
Error while trying to register: Error reading Project.toml: Malformed UUID string: "336ed68f-0bac-5cadda0-87d4-7b16caf5d00b"
```

The Project.toml is as follows:

```
name = "Eirene"
uuid = "9c0f25c4-2ca1-5870-89f6-52640788da1d"
keywords = ["topological data analysis", "persistent homology"]
license = "GNU"
desc = ""
version = "1.1.0"
author = ""

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
CSV = "336ed68f-0bac-5cadda0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
```

Tried to find similar issue reports, but wasn't able to resolve.  Any help would be much appreciated!  Thanks.

**Comment by fredrikekre** [comment]
Where did you get `CSV = "336ed68f-0bac-5cadda0-87d4-7b16caf5d00b"` from? It should be `CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"`.

**Comment by Eetion** [comment]
Thank you!  This resolved the issue.  Regarding the source of the troublesome UUID, it was generated by `(Eirene) pkg> add CSV`.

**Comment by fredrikekre** [comment]
>  Regarding the source of the troublesome UUID, it was generated by (Eirene) pkg> add CSV.

Are you sure? I get the correct one. If you can reproduce this, please file an issue att https://github.com/JuliaLang/Pkg.jl

**Comment by Eetion** [comment]
I tried removing both .toml files and calling `add CSV` again ... this time the correct uuid was generated.  I *did* update some packages after generating the first .toml file and seeing the error.  Perhaps that resolved whatever was going on.  If something similar happens in the future, will know what to do.  Thanks!
