### ISSUE TITLE
404 error page

### ISSUE THREAD

**Issue by devmotion** [JuliaRegistries/Registrator.jl#158]
Hej!

I wanted to install the Github app, but when I try to access https://github.com/apps/juliaregistrar/installations/new I only get a 404 error page. The problem occurs with different web browsers, both on my computer and my phone. Is the link correct? Or has anyone else had this problem and knows how to fix it?

**Comment by nkottary** [comment]
Sorry! We moved the app yesterday and I forgot to update the link in the Readme. I thought github would auto redirect for a while but looks like it does not do that for apps. I've updated the link now. Click the install button on the Readme.

Fixed by 3399d95ece72fd662491615b6ae417279778a536

**Comment by devmotion** [comment]
Now it worked, thanks for the quick fix! :smiley:
