### ISSUE TITLE
Recent commits not associated with JuliaRegistrator GH user

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/Registrator.jl#162]
See e.g. https://github.com/JuliaRegistries/General/pull/835

**Comment by StefanKarpinski** [comment]
See https://github.com/JuliaRegistries/General/pull/835/commits/f6f44c73f1834cc0e455b652bb97dd4c27a93c8a—the user name JuliaRegistrator doesn't link to the JuliaRegistrator user like it used to.

**Comment by nkottary** [comment]
Sorry, made a typo in the gitconfig `user.email` while I was updating the system. Should be OK now.
