### ISSUE TITLE
registrator workflow on Gitlab

### ISSUE THREAD

**Issue by tpapp** [JuliaRegistries/Registrator.jl#174]
Though #54 mentions Gitlab and there seems to be some mechanism for it in the code, it is not clear to me what the workflow is, or whether it is actually supported at this point.

**Comment by omus** [comment]
cc: @christopher-dG

**Comment by christopher-dG** [comment]
Hello, yes the web interface does support registries hosted on GitLab. Is managing a GitLab-hosted registry what you want?

**Comment by tpapp** [comment]
I am wondering if it is possible to register a package **hosted on Gitlab** in the [General registry](https://github.com/JuliaRegistries/General) using a workflow comparable to the one used on Github (ie `@JuliaRegistrator register()`).

**Comment by christopher-dG** [comment]
That will be possible whenever the web interface is up and running for General. Currently it is not deployed. The workflow is simply submitting a web form.

**Comment by christopher-dG** [comment]
You can use https://pkg.julialang.org/registrator now :slightly_smiling_face:

**Comment by StefanKarpinski** [comment]
Shall we close this then or is there more action to take?

**Comment by christopher-dG** [comment]
I think closing is fine, feel free to reopen if there's anything else.
