### ISSUE TITLE
Am admin, public org member and collaborator, but can't trigger release

### ISSUE THREAD

**Issue by quinnj** [JuliaRegistries/Registrator.jl#192]
Help! I should be an admin for a repo, a public org member (JuliaComputing), and listed as a collaborator for the package, but I still can't seem to trigger a release. Is there something else I'm missing? https://github.com/JuliaComputing/IndexedTables.jl/commit/e4177f234be9cc1581e14a1d1b3f9e14c40f7b56

**Comment by fredrikekre** [comment]
Is Registrator installed for the repo?

**Comment by quinnj** [comment]
Ah shoot; I thought for sure we had already done a release, but it looks like it wasn't configured. Thanks and sorry for the noise.
