### ISSUE TITLE
Support `JuliaProject.toml` just like Pkg does

### ISSUE THREAD

**Issue by tkluck** [JuliaRegistries/Registrator.jl#198]
Julia's Pkg supports `JuliaProject.toml` as an alternative to `Project.toml`: see [this link](https://docs.julialang.org/en/v1/manual/code-loading/#Project-environments-1). I chose that option for [StatProfilerHTML.jl](https://github.com/tkluck/StatProfilerHTML.jl/) as it has a significant Perl component and the name `Project.toml` seems too general in that case.

It would make sense for the Registrator not to choke on that, [as it does here](https://github.com/tkluck/StatProfilerHTML.jl/issues/14#issuecomment-508910447). Would that be a difficult addition to make?

**Comment by fredrikekre** [comment]
> Would that be a difficult addition to make?

No, presumably trivial, wanna make a PR? Should just be to look for both alternatives instead of just `Project.toml`.
