### ISSUE TITLE
supporting 0.6 and 1.0

### ISSUE THREAD

**Issue by tomerarnon** [JuliaRegistries/Registrator.jl#216]
In my Project.toml I have 

> [compat]
> julia = "0.6,0.7,1"

and when I try to register the package I get the message:

> Error while trying to register: Julia version < 0.7 not allowed in [compat]

Is it possible to support 0.6 and 1.0 simultaneously?

**Comment by ararslan** [comment]
Pkg3, the system which recognizes Project.toml files, is incompatible with Julia 0.6. For that 0.6 and earlier, you'll need to use a REQUIRE file and register versions separately in the METADATA package registry.

**Comment by tomerarnon** [comment]
Ah I see. Thanks for the info!
