### ISSUE TITLE
Label Patch Releases

### ISSUE THREAD

**Issue by arnavs** [JuliaRegistries/Registrator.jl#217]
I think these should be given extra priority in the merge queue. Currently, all new versions are treated the same (in terms of PR title, etc.) Maybe a label `patch` or something similar could be applied to PRs for patches?

**Comment by DilumAluthge** [comment]
If I’m not mistaken, patch releases are already automatically labeled: https://github.com/JuliaRegistries/General/pulls?q=is%3Apr+is%3Aopen+label%3A%22patch+release%22

Regarding the merge queue, once we have automatic merging (see https://github.com/JuliaRegistries/Registrator.jl/issues/204 and https://github.com/JuliaRegistries/General/pull/3342),
I think that the merge queue will be relatively short. My hope is that most people will make releases that meet the guidelines for automatic merging, and thus relatively few pull requests will require manual review by a human.

**Comment by arnavs** [comment]
Huh. Don't know how I missed those labels.
