### ISSUE TITLE
Broken link of gen_project.jl

### ISSUE THREAD

**Issue by TeroFrondelius** [JuliaRegistries/Registrator.jl#219]
I was following @KristofferC instructions here https://github.com/JuliaFEM/Mortar3D.jl/issues/6 to generate `Project.toml` and it points here: https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml and when I click the [gen_project.jl](https://github.com/JuliaLang/Pkg.jl/blob/master/bin/gen_project.jl) the file is not there.

Can someone update the instructions, I think I am not the only one who would benefit it?

**Comment by fredrikekre** [comment]
24ba3a1cf2608c28b7e50d71ca4013bad320100c
