### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by davidanthoff** [JuliaRegistries/Registrator.jl#221]
Could someone please tag a release? I'm working on a rewrite of PkgDev.jl for a REPL story for tagging packages, and right now that has a dependency on Registrator.jl. Thanks!

**Comment by davidanthoff** [comment]
Bump, could a release please be tagged? CCing the main contributors here: @nkottary, @christopher-dG.

**Comment by christopher-dG** [comment]
@JuliaRegistrator register

**Comment by christopher-dG** [comment]
Oh, are issue comments not supported? :thinking:

**Comment by christopher-dG** [comment]
Oh, my JuliaRegistries membership is not public. @ararslan could you do the honours?

**Comment by ararslan** [comment]
@JuliaRegistrator register

**Comment by christopher-dG** [comment]
I feel like there's a Darth Plagueis meme that belongs here.

**Comment by nkottary** [comment]
Looks like Registrator was not installed on Registrator so it was not getting Registrated. I think it got uninstalled at some point when I moved ownership of the app to JuliaRegistries. I've installed it now.

@JuliaRegistrator register

**Comment by nkottary** [comment]
Updated the URL: https://github.com/JuliaRegistries/General/pull/3965

@JuliaRegistrator register

**Comment by ararslan** [comment]
Registrator refuses to self-registrate

**Comment by nkottary** [comment]
New version updated to 1.0.0 in Project.toml: 6da09d95817ba44bf0b6ce8f215591c9546835b4

@JuliaRegistries register

**Comment by nkottary** [comment]
@JuliaRegistrator register
