### ISSUE TITLE
Registration error - can not find package Logging

### ISSUE THREAD

**Issue by essenciary** [JuliaRegistries/Registrator.jl#232]
Attempting to register a new version of Genie errors out with: 
```
Error while trying to register: Error in (Julia)Project.toml: Package 'Logging' with UUID: 56ddb016-857b-54e1-b83d-db4d58db5568 not found in registry or stdlib
```

The commit: 
https://github.com/GenieFramework/Genie.jl/commit/9b3123b922ee92f46417bc87a4fc6cb228c7be26

**Comment by ronisbr** [comment]
I am getting the same results with Dates:

```
Error while trying to register: Error in (Julia)Project.toml: Package 'Dates' with UUID: ade2ca70-3891-5945-98fb-dc099432e06a not found in registry or stdlib
```

**Comment by KristofferC** [comment]
They are missing from https://github.com/JuliaRegistries/Registrator.jl/blob/master/src/regedit/builtin_pkgs.jl.

**Comment by fredrikekre** [comment]
Why did it suddenly start happening?

**Comment by omus** [comment]
> Why did it suddenly start happening?

I believe this started happening due to https://github.com/JuliaRegistries/General/pull/4169. In that PR entries for Logging and Dates were removed which used the same UUIDs as the stdlibs. I suspect when the original `BUILTIN_PKGS` dict was built these stdlibs were missed as there were included in the general registry

**Comment by omus** [comment]
I took a quick inventory of differences between the stdlibs and `BUILTIN_PKGS`:

- Removed from General registry in JuliaRegistries/General#4169 and missing from `BUILTIN_PKGS`
    - Dates
    - LibGit2
    - Logging
    - REPL
- Still included in General registry and missing from `BUILTIN_PKGS`: 
    - SHA
- Never included in General registry and missing from `BUILTIN_PKGS`:
     - Makefile
     - Markdown

Note that when the same package name was included in the registry and as a stdlib the UUIDs were identical

**Comment by nkottary** [comment]
@omus Thanks for the list. I've put up a fix here: https://github.com/JuliaRegistries/Registrator.jl/pull/233. The new list has everything except Makefile. I couldn't find that one.

**Comment by omus** [comment]
I think I accidentally included the actual "Makefile" file when doing my inventory. I did say I did it quick 😅
