### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by davidanthoff** [JuliaRegistries/Registrator.jl#242]
Could someone please tag a new version? There are some important fixes on `master` that I'd like to use in my rewrite of PkgDev.jl. Thanks :)

**Comment by DilumAluthge** [comment]
It looks like the version number needs to be bumped. (The version in `Project.toml` is `1.0.0` on `master`, and the latest released version is `1.0.0`.)

Want to make a PR to bump the version number?

**Comment by davidanthoff** [comment]
Done! https://github.com/JuliaRegistries/Registrator.jl/pull/245

This is why we need https://github.com/JuliaRegistries/TagBot/issues/34, so that we don't need to do any of this by hand :)

**Comment by nkottary** [comment]
@JuliaRegistrator register

**Comment by nkottary** [comment]
@JuliaRegistrator register

**Comment by nkottary** [comment]
@JuliaRegistrator register

**Comment by davidanthoff** [comment]
I should add that from my end I no longer need tagged versions of Registrator.jl, now that we have RegistryTools.jl.

**Comment by DilumAluthge** [comment]
Can this issue be closed now?
