### ISSUE TITLE
Document auto-merging

### ISSUE THREAD

**Issue by crstnbr** [JuliaRegistries/Registrator.jl#243]
Currently, README.md says
>We will soon have a CI system to check and auto-merge without human intervention.

We should update this and point to the automatic merging guidelines. Do they live somewhere "official" that we could point to? 

I only know of https://github.com/JuliaRegistries/General/issues/3673 and https://discourse.julialang.org/t/announcement-automatic-merging-for-the-general-registry/29961.

I'd make a PR after above's question is resolved.

**Comment by DilumAluthge** [comment]
I believe this was fixed by #244
