### ISSUE TITLE
Move RegEdit.jl into separate repo

### ISSUE THREAD

**Issue by davidanthoff** [JuliaRegistries/Registrator.jl#246]
Would folks be open to moving RegEdit into a separate standalone package?

I'm almost done with a revamp of PkgDev.jl, and it would be much nicer if that didn't have this very large dependency trail that Registrator.jl brings along currently.

**Comment by davidanthoff** [comment]
Ok, I started https://github.com/davidanthoff/PkgRegistryEditTools.jl. Happy to move that repo to some other organization. Tests don't yet pass.

It would probably be good if we tried to get this over the finish line soon, so that we don't end up with a situation where the code in Registrator moves on before we make the transition.

**Comment by davidanthoff** [comment]
Ok, tests now pass. Was just a problem in the test code itself on Windows, but that is fixed now. I'll try to open a PR against Registrator.jl tomorrow that takes out RegEdit and uses the external package instead. If someone beats me to that, I'd be more than happy :)

**Comment by davidanthoff** [comment]
Oh, one more thing: Are folks ok with the name `PkgRegistryEditTools`? Given that this package will probably not be used by any end-user and is pretty obscure, I didn't want to "waste" a good short name like `RegEdit` on that package. But I don't really care, so happy to just follow any other name suggestion.

Also, can I move the package into the `JuliaRegistries` org? Is that where it should be?

**Comment by davidanthoff** [comment]
Alright, the PR for Registrator.jl is also done, [here](https://github.com/JuliaRegistries/Registrator.jl/pull/247).

Can someone please give me access rights for JuliaRegistries so that I can transfer PkgRegistryEditTools.jl to that org? I believe I need enough rights so that I can create repos in that org.

Also, everyone happy with the new package name?

**Comment by fredrikekre** [comment]
Why is Pkg in the name? RegistryTools seems enough to me.

**Comment by davidanthoff** [comment]
Alright, RegistryTools.jl registration is pending: https://github.com/JuliaRegistries/General/pull/5378, once that is done we can merge the PR here in Registrator.jl.
