### ISSUE TITLE
False positive on Julia version

### ISSUE THREAD

**Issue by randyzwitch** [JuliaRegistries/Registrator.jl#249]
Get the following message: `Error while trying to register: Julia version < 0.7 not allowed in [compat]`, minimum julia version is 1.1

```
name = "OmniSci"
uuid = "085fdc97-bbf0-5359-b689-34bac5cd65e1"
author = ["Randy Zwitch <randy.zwitch@omnisci.com>"]
version = "0.6.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DecFP = "55939f99-70c6-5e9b-8bb0-5071ed7d61fd"
Decimals = "abce61dc-4473-55a0-ba07-351d65e31d42"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Thrift = "8d9c9c80-f77e-5080-9541-c6f69d204e22"

[compat]
DataFrames = "~0.19.0"
DecFP = "~0.4.8"
Decimals = "~0.4.0"
GeoInterface = "~0.4.0"
LibGEOS = "~0.5.0"
Thrift = "~0.6.0"
julia = "≥ 1.1.0, < 1.4"
```

https://github.com/omnisci/OmniSci.jl/commit/c5151d0d3b4c87980a2ee35a495dd22313f3aa44#diff-910a7b3ca0075d545dcec45cb7335ca9

**Comment by fredrikekre** [comment]
It's the union, so `"≥ 1.1.0, < 1.4"` means `[0.0.0, ∞)`.

**Comment by randyzwitch** [comment]
I don't understand how that resolves to `[0.0.0, ∞)` ...if I'm supposed to put upper bounds so I can have auto-merging, but then I put `1.1`, how do I specify that I don't mean infinitely high versions of Julia, just 1.1, 1.2 and 1.3?

**Comment by fredrikekre** [comment]
> I don't understand how that resolves to `[0.0.0, ∞)` ...

The union of `[1.1.0, ∞)` and `[0.0.0, 1.4.0)` is `[0.0.0, ∞)`.

> if I'm supposed to put upper bounds so I can have auto-merging, but then I put 1.1, how do I specify that I don't mean infinitely high versions of Julia, just 1.1, 1.2 and 1.3?

See https://julialang.github.io/Pkg.jl/v1/compatibility/. Basically, you should use
```toml
julia = "1.1"
```
which then means `[1.1.0, 2.0.0)`.

**Comment by randyzwitch** [comment]
Okay, I understand the union part. The second part though, I know for certain that my package does not pass against nightly, so [1.1.0, 2.0.0) is incorrect:

https://travis-ci.org/omnisci/OmniSci.jl/jobs/612407587

**Comment by fredrikekre** [comment]
But that looks to be DecFP's fault, not yours.

**Comment by randyzwitch** [comment]
Sure, but it's still an issue that is currently unresolved for anyone who tries to use nightly.

**Comment by fredrikekre** [comment]
Thats life on nightly :man_shrugging: 

You should never have to bound julia like that since then it is a julia bug which should be fixed before release (julia should not break until 2.0). And IMO, especially when its another of your dependencies fault you shouldn't do this.

Btw, looks like DecFP works on its master branch, so a new release of that package should fix everything.

**Comment by fredrikekre** [comment]
https://github.com/JuliaMath/DecFP.jl/pull/101

**Comment by randyzwitch** [comment]
Ok, thanks. I'll change it to 1.1
