### ISSUE TITLE
Registrator encounters unexpected error in registration after yanked release

### ISSUE THREAD

**Issue by CiaranOMara** [JuliaRegistries/Registrator.jl#259]
The Registrator returned `Error while trying to register: Unexpected error in registration` when attempting to register [GenomicFeatures v1.0.2](https://github.com/BioJulia/GenomicFeatures.jl/commit/e0783f58869a890662da752953551996a99469ff) after GenomicFeatures v1.0.1 was [yanked](https://github.com/JuliaRegistries/General/pull/7590). The Registrator succeeded after the yank was reverted.

cc @DilumAluthge

**Comment by CiaranOMara** [comment]
Possibly re-encountered at https://github.com/BioJulia/GenomicFeatures.jl/commit/e7ce4e36210407fb9f05e36c303c562aad30d9c0.

**Comment by DilumAluthge** [comment]
So, if you ever need to yank a release for any reason, you are then permanently unable to ever make a new release with Registrator.jl.

**Comment by DilumAluthge** [comment]
Unfortunately, this bug is difficult to debug without access to the logs.
