### ISSUE TITLE
Error while trying to register: Unexpected error in registration

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/Registrator.jl#272]
https://github.com/JuliaGizmos/JSExpr.jl/commit/8aecd2cd6f0fd415e61cce1ba395f3d11b234b07#commitcomment-37777787

**Comment by DilumAluthge** [comment]
I think this is the yanking issue.

**Comment by nkottary** [comment]
Yes

**Comment by fredrikekre** [comment]
Thanks, so the TOML implementation tries to recursively sort...
