### ISSUE TITLE
ERROR: Registration failed: Changing UUIDs is not allowed

### ISSUE THREAD

**Issue by bradlindblad** [JuliaRegistries/Registrator.jl#283]
I submitted package Schrute while in a git repo with a certain UUID. Since then, I had to scrap that repo and make another one from scratch. The error in the title is what I receive when trying to push an update to that repo. Is there a way to push to my existing repo with a new UUID? Or is there a way to kill the existing package in the registry?

**Comment by DilumAluthge** [comment]
Just change the UUID in your new repo to match the UUID in the General registry.

We do not allow you to modify the UUID in the registry.

**Comment by bradlindblad** [comment]
So simple, thank you sir
