### ISSUE TITLE
registrator not triggered

### ISSUE THREAD

**Issue by andrewning** [JuliaRegistries/Registrator.jl#291]
I've registered a couple packages in the past, but today it isn't triggering for some reason.  I double checked that I added the app to this repo and added a comment: https://github.com/byuflowlab/CCBlade.jl/commit/f6484aea0b2050544876e5a2ebfd5e5b85fa0e70
Normally the registrator auto-comment has been essentially instantaneous.  Do I just need to wait longer?

**Comment by rschwarz** [comment]
I'm having the same problem today:
https://github.com/rschwarz/Diderot.jl/commit/588d7ad02367aba20e7a9aeb8f825b312ae8abd5

The Registrator GitHub is installed and active on all of my projects, and I've tried to add a second comment a couple of minutes later.

From my past experience, the PR was usually created an instant later.

**Comment by nkottary** [comment]
We had a DNS outage on the server where Registrator runs. It is fixed now and should be okay.
