### ISSUE TITLE
@JuliaRegistrator register: How to know if everything went fine ?

### ISSUE THREAD

**Issue by sylvaticus** [JuliaRegistries/Registrator.jl#295]
`@JuliaRegistrator register` "If something is incorrect, adjust, and redo step 2."

How do I ever know if everything went fine or something is incorrect ?

**Comment by sylvaticus** [comment]
Lead by the response of the robot, I managed to get the pull request for registration triggered by commenting on my own repository, but it didn't work putting [THAT PHRASE] in the commit message.
Also the [web interface](https://eu.pkg.julialang.org/registrator/) returns a White Page Of Death

**Comment by nkottary** [comment]
You need to *comment* on the commit with [THAT PHRASE].

Updated web UI link: https://github.com/JuliaRegistries/Registrator.jl/pull/297/files

**Comment by sylvaticus** [comment]
Ah, ok. It would be nice to allow [THAT PRASE] to be put directly in the commit message, without the need to commit and then comment the commit, but maybe that would require a different architecture, thank you for clarifying.
