### ISSUE TITLE
WebUI documentation is insufficient

### ISSUE THREAD

**Issue by schlichtanders** [JuliaRegistries/Registrator.jl#301]
Hi, just tried to register my first package via juliahub (as one of the two recommended ways).
However I reach this Web page
<img width="1792" alt="Screenshot 2020-07-30 at 14 01 14" src="https://user-images.githubusercontent.com/4255480/88920442-2b6c2f80-d26d-11ea-9403-5fa1f59d4e3f.png">

Where the two fields `PackageUrl` and `PackageName` are completely greyed out - no way to fill them in - and the remaining fields are quite unintuitive to setup (my current best guess is that it is simply not possible but buggy)

I am now falling back to using the Github Extension, luckily my package is in github and not in gitlab.

Would be great if this could be better supported, either by 
* providing the necessary information about how to do it (the current [link](https://juliaregistries.github.io/Registrator.jl/stable/webui/#Usage-(For-Package-Maintainers)-1) seems outdated, at least does not apply to the screenshot you see from juliahub)
* or fixing juliahub registration WebUI (if the greyed-out fields should actually be fillable)

**Comment by fredrikekre** [comment]
https://github.com/JuliaComputing/JuliaHub

**Comment by nkottary** [comment]
Click on the "grant additional privileges" link to grant JuliaHub permissions to your GitHub repositories. Then the fields will be unlocked.

**Comment by StefanKarpinski** [comment]
But please do open an issue on JuliaHub to discuss what could be done to make this clearer!
