### ISSUE TITLE
Error: Changing package repo URL not allowed (but, not URL changed)

### ISSUE THREAD

**Issue by kibaekkim** [JuliaRegistries/Registrator.jl#303]
I am trying to release a patch, but the bot returned an error:
https://github.com/kibaekkim/BundleMethod.jl/commit/f173e8436943c71579cb4e8fc55f757e46add43c#commitcomment-41194582

I checked my recent PR: https://github.com/JuliaRegistries/General/pull/17971 and confirmed that the URL has not been changed since then.

**Comment by DilumAluthge** [comment]
Package registrations are temporarily disabled due to a breaking change in the GitHub API.

More details are available here: https://discourse.julialang.org/t/pkg-downtime-incident/44288
