### ISSUE TITLE
Spurious package URL error

### ISSUE THREAD

**Issue by joehuchette** [JuliaRegistries/Registrator.jl#304]
I recently bumped my [BARON.jl]() package after adding a small feature, and tagging JuliaRegistrator [repeatedly gives the error](https://github.com/joehuchette/BARON.jl/commit/f227a61d6038643f9b06224f68b60f11fda79e7b#commitcomment-41194553)
```
Error while trying to register: Changing package repo URL not allowed, please submit a pull request with the URL change to the target registry and retry.
```
Git blame says I have haven't changed the package URL in 5 months (last patch release was ~2 months ago), and I haven't changed anything on Github either (e.g. directory name, username, etc.).

Any suggestions on how to proceed?

**Comment by DilumAluthge** [comment]
Package registrations are temporarily disabled:

**Comment by DilumAluthge** [comment]
Package registrations are temporarily disabled due to a breaking change in the GitHub API.

More details are available here: https://discourse.julialang.org/t/pkg-downtime-incident/44288?u=dilumaluthge

**Comment by arnavs** [comment]
Would be nice if this could be posted on the README or something similar.

**Comment by arnavs** [comment]
Looks resolved for me now.
