### ISSUE TITLE
Unexplained URL change

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaRegistries/Registrator.jl#305]
I just tried tagging a new release to FillArrays.jl in 

https://github.com/JuliaArrays/FillArrays.jl/commit/6a1b63091ee671a13ed4f009d215ed4a34aaa2c8 

but got an error about change to URL that doesn't make sense, as the URL has not changed:

https://github.com/JuliaRegistries/General/blob/master/F/FillArrays/Package.toml

**Comment by dlfivefifty** [comment]
Just realised this is a dup: https://github.com/JuliaRegistries/Registrator.jl/issues/304

Please leave this issue open until its reenabled or you may get more dups.

**Comment by DilumAluthge** [comment]
Resolved now.
