### ISSUE TITLE
Improve documentation on how to setup issue-triggered registration

### ISSUE THREAD

**Issue by ablaom** [JuliaRegistries/Registrator.jl#306]
I can successfully register a new package at Juliahub but what's the extra step to enable issue-triggered registration? (Which works fine for some of my packages but not newer ones). There does not seem to be any instruction for this on the README.md for this. It just says "First, install the app on your package(s) as mentioned above" but there is no longer any instructions or other reference about the (now obsolete??) GitHubApp.

See, for example this issue comment which @JuliaRegistrator ignores:

https://github.com/alan-turing-institute/MLJMultivariateStatsInterface.jl/issues/4#issuecomment-706785185

**Comment by DilumAluthge** [comment]
You need to install the GitHub App on that repository.

The GitHub app is definitely not obsolete.

**Comment by DilumAluthge** [comment]
Just click the blue button in this section: https://github.com/JuliaRegistries/Registrator.jl#install-registrator

**Comment by ablaom** [comment]
Okay. I feel pretty stupid. 😳

**Comment by DilumAluthge** [comment]
We could probably improve the docs a little bit.
