### ISSUE TITLE
JuliaRegistrator removes labels from a registration PR when it updates it

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/Registrator.jl#308]
e.g. https://github.com/JuliaRegistries/General/pull/22879

**Comment by fredrikekre** [comment]
I think we use https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#update-an-issue but should probably use https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#add-labels-to-an-issue

**Comment by DilumAluthge** [comment]
Bump. Is there any update on this?

**Comment by DilumAluthge** [comment]
@ericphanson and I would like to use labels to streamline AutoMerge a little bit. But that will be inconvenient if Registrator keeps removing labels.
