### ISSUE TITLE
Registrator bot unresponsive?

### ISSUE THREAD

**Issue by tamasgal** [JuliaRegistries/Registrator.jl#320]
The bot does not seem to respond anymore and I have not changed any configuration on my side. See for example: https://github.com/tamasgal/UnROOT.jl/commit/0aa6c8c56afdcf0343764ecb4a79669034d397a0#comments

This is the last commit where it worked (August 2020): https://github.com/tamasgal/UnROOT.jl/commit/6b0ab30a4dbecc911df5d332e843045dc2427199

I also tried creating an issue: https://github.com/tamasgal/UnROOT.jl/issues/15

The integration looks OK too:

![Screenshot 2021-01-27 at 23 35 56](https://user-images.githubusercontent.com/1730350/106063417-6f46d100-60f8-11eb-914c-6dd7b4045070.png)

**Comment by DilumAluthge** [comment]
@nkottary

**Comment by ablaom** [comment]
juliahub also not responding

**Comment by rafaqz** [comment]
Same issue

**Comment by DilumAluthge** [comment]
This is fixed now.
