### ISSUE TITLE
Request to look for the main branch as well

### ISSUE THREAD

**Issue by tsano430** [JuliaRegistries/Registrator.jl#321]
Hi all, 

The specification of GitHub has recently been changed as follows: 
https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

So, I'd like the registrator to look for the project file in the master or main branch by default. 

Thanks!

**Comment by nkottary** [comment]
This is fixed for the comment bot in #328 and in the JuliaHub UI as well.
