### ISSUE TITLE
JuliaRegistrator call doesn't trigger the bot

### ISSUE THREAD

**Issue by tomchor** [JuliaRegistries/Registrator.jl#327]
I'm trying to trigger a new version by issuing `@JuliaRegistrator register` [here](https://github.com/tomchor/Oceanostics.jl/issues/10) but nothing is happening. Am I missing something?

The registrator should be set-up on that repo. I was able to trigger it [here](https://github.com/tomchor/Oceanostics.jl/pull/9#issuecomment-817170042) although it threw me an error because it doesn't work on PRs.

**Comment by DilumAluthge** [comment]
Probably Nishanth will need to look at the logs. I've pinged him in that issue.

**Comment by nkottary** [comment]
Should be fixed by JuliaRegistries/Registrator.jl#328
