### ISSUE TITLE
"@JuliaRegistrator register" does not result in bot activity

### ISSUE THREAD

**Issue by chipkent** [JuliaRegistries/Registrator.jl#331]
I'm trying to register a new package using GitHub actions.  This commit calls `@JuliaRegistrator register`, but I do not see any Registrator bot activity.

https://github.com/chipkent/RateLimiter.jl/commit/ab156d085db8676466e0118f88ba060804b585bb

**Comment by fredrikekre** [comment]
1. Is the bot installed on the repository?
2. Does it work if you comment yourself instead?

**Comment by chipkent** [comment]
It does not work if I comment myself.

I'm guessing this is a problem with the bot not being installed.  The instructions for bot installation are not very good.  Can you please point me in the right direction?

I am concerned that the bot install requires me to follow the steps at https://juliahub.com/ui/Registrator.  That URL requires me to grant full write access to all of my open repositories.  This looks like a concerning security problem.

**Comment by fredrikekre** [comment]
Press "Install App" here: https://github.com/JuliaRegistries/Registrator.jl#install-registrator and select the repositories you want it to be active at.  Requires read access (not write).

**Comment by chipkent** [comment]
That fixed it.  I would have never figured that out from the readme, so I proposed a change.

https://github.com/JuliaRegistries/Registrator.jl/pull/332
