### ISSUE TITLE
Add link to bio

### ISSUE THREAD

**Issue by fonsp** [JuliaRegistries/Registrator.jl#333]
Perhaps you can add a link to this repository in the bio of https://github.com/JuliaRegistrator ? It took me quite long to find this readme (I forgot that I needed to install the app).

**Comment by fonsp** [comment]
Also I think `eco-system` should be `ecosystem`

**Comment by DilumAluthge** [comment]
> Perhaps you can add a link to this repository in the bio of https://github.com/JuliaRegistrator ? It took me quite long to find this readme (I forgot that I needed to install the app).

@nkottary

**Comment by nkottary** [comment]
Done.
