### ISSUE TITLE
Registrator hardcodes `master` instead of using the default branch

### ISSUE THREAD

**Issue by harshangrjn** [JuliaRegistries/Registrator.jl#336]
Hello, I am trying to register a new package and have followed the instructions as suggested in the README.md file. Basically installed the Julia Registrator App, added the version number in `Project.toml` and added the comment in the issues as can be seen here: https://github.com/harshangrjn/LaplacianOpt.jl/issues/14 

But for some reason, the registrator bot is not picking up the package for the first release. Let me know if am I missing something. Thanks a lot!

**Comment by DilumAluthge** [comment]
https://github.com/harshangrjn/LaplacianOpt.jl/issues/14#issuecomment-839330824

**Comment by nkottary** [comment]
Fixed in https://github.com/JuliaRegistries/Registrator.jl/pull/328 and deployed.
