### ISSUE TITLE
Registering fails when you mention a tag

### ISSUE THREAD

**Issue by nkottary** [JuliaRegistries/Registrator.jl#339]
This is after https://github.com/JuliaRegistries/Registrator.jl/pull/335 was merged.

As pointed out in that PR we need the `origin/` prefix for `git rev-parse` so that we can get the tree SHA for non-default branches. It does not work however when we use a tag. For example `origin/v0.4`. So to solve this issue I think we should have two input fields one for Tag and another for Branch instead of having both in the same field. So now when we get a Tag we prefix with `tags/`. For example, `tags/v0.4` which works.

**Comment by StefanKarpinski** [comment]
If we make a bare mirror clone of the upstream repo then we would get all of the branches, tags, etc.

**Comment by StefanKarpinski** [comment]
Even without that, it seems better to try and see if somethings works as a tag and if that fails then try it as a branch, rather than complicating the UI further.

**Comment by nkottary** [comment]
Thanks! `--bare` gives us what we need. There is also `--mirror` as you pointed out. In addtion to remote branches and tags which `--bare` gives us, `--mirror` gives all [refs](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---mirror) as well but I don't know we need that.

**Comment by StefanKarpinski** [comment]
Yes, bare seems sufficient. I can never remember what the difference is.
