### ISSUE TITLE
Confusing instructions from the Registrator

### ISSUE THREAD

**Issue by NicolasL-S** [JuliaRegistries/Registrator.jl#341]
I'm trying to update my package using the Registrator at JuliaHub (from 0.1.0 to 0.2.0). There was a mistake in my Project.toml file, and the registrator commented: 

"(...) After you have fixed the AutoMerge issues, simple retrigger Registrator, which will automatically update this pull request. You do not need to change the version number in your `Project.toml` file. (...)" 

I corrected the error and triggered the Registrator again. But now I get the message:

"Please update the version number in the package's Project.toml before registering a new version. The current version number is already tagged to a different commit". 

Am I doing something wrong?

**Comment by nkottary** [comment]
It is necessary that the commit you register is the same as the commit on your tag for the same version.

As the error message explains you already have a tag (release) on your package with the same version number as the one in your Project.toml that points to a different commit vs the commit on your main or master branch. You could either:
1) Delete this tag and the release from GitHub and re-register the package. You can then create the tag and release once the registration has gone through. You could also install the [TagBot](https://github.com/JuliaRegistries/TagBot) which will automatically create the tag and release for you. Or,
2) Create a branch off of your existing release and then mention that branch in the registration form.

1 registers your default branch (main or master) and 2 registers your existing tag. Hope that helps.

**Comment by NicolasL-S** [comment]
Thanks a lot. I did option 1 and it worked perfectly. I had no ideas about tags. The learning curve for Julia is gentle, but for GitHub, the documenter, the registrator, etc. that requires stamina.
