### ISSUE TITLE
"it looks like you are not a publicly listed member/owner in the parent organization"

### ISSUE THREAD

**Issue by timholy** [JuliaRegistries/Registrator.jl#351]
...but that's not true, and GitHub lets me access the settings page.

https://github.com/JuliaImages/ImageCore.jl/commit/ff7afc048c5832d8f3e6269f40ed06c4399cec7b

**Comment by DilumAluthge** [comment]
Is your membership public?

**Comment by DilumAluthge** [comment]
E.g. go to https://github.com/orgs/JuliaImages/people in an incognito browsing window.

**Comment by DilumAluthge** [comment]
If you don't see yourself there, you'll need to publicize your membership as described here: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership

**Comment by timholy** [comment]
Thanks, that was it! I had no idea it was private. Fixed now.

**Comment by StefanKarpinski** [comment]
GitHub defaults all organization membership to private, for some reason. Very annoying.
