### ISSUE TITLE
Registration of new package fails

### ISSUE THREAD

**Issue by sapal6** [JuliaRegistries/Registrator.jl#359]
I am trying to register my [package](https://github.com/sapal6/nbdev.jl.git) for the first time. I was using the Registration bot but it returns an error comment - "Error while trying to register: Changing package names not supported yet".

I also tried to register the package via web but got the same error there as well.

**Comment by DilumAluthge** [comment]
Please read the section on "How do I rename an existing registered package".

https://github.com/JuliaRegistries/General/blob/master/README.md#how-do-i-rename-an-existing-registered-package

**Comment by sapal6** [comment]
Thanks @DilumAluthge . Will follow the instructions given in the link.
