### ISSUE TITLE
error while trying to register new package rev

### ISSUE THREAD

**Issue by avigliotti** [JuliaRegistries/Registrator.jl#378]
I am trying to register a new rev of this [package](https://github.com/avigliotti/AD4SM.jl) but when I invoke the registrator [here](https://github.com/avigliotti/AD4SM.jl/issues/8) I get this error

`Error while trying to register: "Pre-release version not allowed"`

how can I fix this?

**Comment by fredrikekre** [comment]
The error message is pretty descriptive, no? You can not have `-beta` in your version here: https://github.com/avigliotti/AD4SM.jl/blob/bbeeb379138efd338d867b442d416a141a9e7893/Project.toml#L4

**Comment by avigliotti** [comment]
many thanks, was not aware of that
