### ISSUE TITLE
Fail to register??

### ISSUE THREAD

**Issue by aumpierre-unb** [JuliaRegistries/Registrator.jl#385]
I have recently had a new package accepted (New package: InternalFluidFlow v0.1.0 #66536). It passed all checks but I don't know weather it is or is not registered. What to do now? Is there an action I should do in order to register and I am missing it? Thank you for your help!

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/pull/66536#issuecomment-1225708197
