### ISSUE TITLE
Fail to register New package: McCabeThiele v0.1.1 #69238

### ISSUE THREAD

**Issue by aumpierre-unb** [JuliaRegistries/Registrator.jl#393]
Hi, I'm having a hard time to register New package: McCabeThiele v0.1.1 #69238. It passed all checks and I commented "@JuliaRegistrator register [noblock]" three days ago. Can't see what's wrong. Would you please help me on that? Thanks!

**Comment by ericphanson** [comment]
I replied there: https://github.com/JuliaRegistries/General/pull/69238#issuecomment-1264699811

By the way, you should not call `JuliaRegistrator` in the General PR; it doesn't do anything. You just need to wait for automerge.
