### ISSUE TITLE
Listing in https://juliapackages.com/

### ISSUE THREAD

**Issue by orenbenkiki** [JuliaRegistries/Registrator.jl#414]
Does registering a package using `Registrator.jl` automatically add the package to https://juliapackages.com/ ?
Asking because a package I registered several days ago (`NestedTests.jl`), which works with `Pkg.add`, doesn't appear in the list.
Do I need to take another action to make it appear there?

**Comment by ericphanson** [comment]
I think the answer is no, but I would suggest filing an issue at https://github.com/djsegal/julia_packages and asking there to reach the maintainer of that project.

**Comment by orenbenkiki** [comment]
"No" as in it isn't expected to be automatic,
or "no" as in I'm not expected to take any further action? :-)
At any rate, I'll pursue it in `julia_packages` - thanks.

**Comment by ericphanson** [comment]
Sorry, that wasn’t very clear of me. I don’t think there’s anything setup to “push” to juliapackages or trigger something there, but also I don’t think users are supposed to need to do anything if everything is working correctly. My guess is they have a cron job setup to ingest new packages and either you need to wait longer or it’s broken currently. But either way I think asking over there is the way to go.
