### ISSUE TITLE
Registration of a new package fails 

### ISSUE THREAD

**Issue by andreasvarga** [JuliaRegistries/Registrator.jl#437]
I am trying to register a new package [PeriodicMatrices.jl](https://github.com/andreasvarga/PeriodicMatrices.jl) but I received the following error message:

[JuliaRegistrator](https://github.com/JuliaRegistrator) commented on [102d4a3](https://github.com/andreasvarga/PeriodicMatrices.jl/commit/102d4a3191eee93402156e8110bf80ac168f9c81) [Oct 24, 2024](https://github.com/andreasvarga/PeriodicMatrices.jl/commit/102d4a3191eee93402156e8110bf80ac168f9c81#commitcomment-148312457)

Error while trying to register: Changing package names not supported yet

I don't understand this message. I am aware of #359 and of the suggestion to handle, but I wonder why should I rename my package or why to generate a new UUID. I would appreciate receiving help on this issue.

**Comment by ericphanson** [comment]
The UUID is in use already: https://github.com/JuliaRegistries/General/blob/ede23c2a21fc1c4e6849b209e11b06eaf33c48e3/K/KRPC/Package.toml#L2

either you got extraordinarily unlucky with a uuid4 collision, or maybe you copied the uuid from somewhere?

**Comment by andreasvarga** [comment]
I generated a new UUID. Thanks for the fast response. The UUID I generated myself (possibly relying on the default setting for the random number generator seed).

**Comment by andreasvarga** [comment]
The registration started as usual. So, I am closing this issue.
