### ISSUE TITLE
JuliaRegistrar should remove the branch when the PR is merged

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/Registrator.jl#89]

**Comment by christopher-dG** [comment]
TagBot already reacts to PR closure on the registry and could do this easily, let me know if I should add that functionality.

**Comment by fredrikekre** [comment]
Seems like not a job for the tag-bot; and branches for non-tag-bot packages should also be removed.

**Comment by christopher-dG** [comment]
I agree that it's a bit smelly for separation-of-concerns reasons, but FWIW it would work for all PRs, not just ones for packages that have the bot enabled.

**Comment by fredrikekre** [comment]
Oh, thats right. But that would require the tag-bot to have write access to the registry.

**Comment by christopher-dG** [comment]
It already does have that access actually, since it's installed for PR commenting.

**Comment by christopher-dG** [comment]
Or perhaps we should just install something like this: https://github.com/svanboxel/delete-merged-branch

**Comment by StefanKarpinski** [comment]
I like using the delete-merged-branch integration—less code that we need to write and maintain.

**Comment by fredrikekre** [comment]
bors can do it too.

**Comment by christopher-dG** [comment]
delete-merged-branch is installed for this repo, and working quite well.
